-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgfiSg+CELFxWbby2G
dawQhtws4x0bdBkQNSWIngXgkwKgCgYIKoZIzj0DAQehRANCAASPWnqMoMWejPBr
v2Yre61g3YpRKmmxoFqIv4Rap4F0hOft98QS1JzRtjtrLAkdwDq9AsIvVCmYj/z9
t3evDJR9
-----END PRIVATE KEY-----