#!/bin/bash

# Push Notifications Installation Script
# Run this from the GermanTelcB1App directory

echo "🚀 Installing Push Notifications for German Telc B1 App"
echo ""
echo "Step 1: Installing @react-native-firebase/messaging..."
npm install @react-native-firebase/messaging

echo ""
echo "Step 2: Installing iOS pods..."
cd ios && pod install && cd ..

echo ""
echo "✅ Packages installed successfully!"
echo ""
echo "📋 Next steps (manual):"
echo ""
echo "1. Uncomment FCM Service code:"
echo "   - Open: src/services/fcm.service.ts"
echo "   - Uncomment: import messaging from '@react-native-firebase/messaging';"
echo "   - Uncomment all method implementations"
echo "   - Remove warning messages"
echo ""
echo "2. Add background handler to index.js:"
echo "   - Open: index.js"
echo "   - Add before AppRegistry.registerComponent:"
echo ""
echo "   import messaging from '@react-native-firebase/messaging';"
echo "   messaging().setBackgroundMessageHandler(async remoteMessage => {"
echo "     console.log('Background message:', remoteMessage);"
echo "   });"
echo ""
echo "3. Configure iOS in Xcode:"
echo "   - Open: ios/GermanTelcB1App.xcworkspace"
echo "   - Select target → Signing & Capabilities"
echo "   - Add 'Push Notifications' capability"
echo "   - Add 'Background Modes' capability"
echo "     → Check 'Remote notifications'"
echo ""
echo "4. Upload APNs certificate to Firebase:"
echo "   - Go to: https://console.firebase.google.com"
echo "   - Project Settings → Cloud Messaging → iOS"
echo "   - Upload your APNs Key or Certificate"
echo ""
echo "5. Test notifications:"
echo "   - Run the app"
echo "   - Login"
echo "   - Go to Settings → Enable notifications"
echo "   - Check Firestore for fcmToken"
echo "   - Send test from Firebase Console"
echo ""
echo "📚 Documentation:"
echo "   - Full guide: FCM_SETUP.md"
echo "   - Quick reference: NOTIFICATION_SUMMARY.md"
echo "   - Implementation details: ../../PUSH_NOTIFICATIONS_IMPLEMENTATION.md"
echo ""
echo "Done! 🎉"

