/**
 * DELE Spanish B1 Exam Configuration
 * 
 * This is the configuration for the existing DELE Spanish B1 exam app.
 * It maintains backward compatibility with the current setup.
 */

import { ExamConfig, ExamSectionConfig, MockExamConfig } from '../exam-config.types';

export const deleSpanishB1Config: ExamConfig = {
  // Basic Identity
  id: 'dele-spanish-b1',
  language: 'spanish',
  level: 'B1',
  provider: 'dele',
  
  // App Identity
  appName: 'DeleSpanishB1',
  displayName: 'Spanish DELE B1',

  bundleId: {
    android: 'com.mhamada.deleb1spanish',
    ios: 'com.mhamada.deleb1spanish',
  },
  
  // Theme Configuration
  theme: 'default',
  
  // Firebase Collections (keeping existing collection names for backward compatibility)
  firebaseCollections: {
    examData: 'spanish_b1_dele_exam_data',              // Existing collection
    userProgress: 'users/{uid}/dele_spanish_b1_progress/data',   // Fixed: Must be 4 segments for .doc() to work
    completions: 'users/{uid}/dele_completions_spanish_b1',      // Lang and level in path (3 segments to allow appending 3 more for doc)
    streaks: 'users/{uid}/streaks/dele-spanish-b1',              // Daily streaks tracking per exam
    vocabularyData: 'vocabulary_data_spanish_b1',           // Vocabulary words collection
    vocabularyProgress: 'users/{uid}/dele_vocabulary_progress_spanish_b1/data', // User vocabulary progress
    speakingDialogues: 'users/{uid}/dele_speaking_dialogues_spanish_b1', // Speaking assessments
  },
  
  // Exam Metadata (from existing exam-info.json)
  metadata: {
    cefrLevel: 'B1',
    totalDurationMinutes: 200,
    totalMaxPoints: 100,
    passingScore: 60,
  },
  
  // All features enabled for Spanish DELE B1
  features: {
    reading: true,
    listening: true,
    writing: true,
    speaking: true,
    grammar: true,
  },
  
  // Store IDs
  storeIds: {
    android: 'com.mhamada.deleb1spanish',
    ios: '6758210099',
  },

  ads: {
    appID: {
      android: 'ca-app-pub-5101905792101482~3723260491',
      ios: 'ca-app-pub-5101905792101482~5306475915',
    },
    banner: {
      android: 'ca-app-pub-5101905792101482/9245720926',
      ios: 'ca-app-pub-5101905792101482/7657307086',
    },
    rewarded: {
      android: 'ca-app-pub-5101905792101482/1138116297',
      ios: 'ca-app-pub-5101905792101482/8544342339',
    },
    userSupport: {
      android: 'ca-app-pub-5101905792101482/4437576361',
      ios: 'ca-app-pub-5101905792101482/4653198789',
    },
    vocabularyBuilder: {
      android: 'ca-app-pub-5101905792101482/8825034623',
      ios: 'ca-app-pub-5101905792101482/9946544608',
    },
    appOpen: {
      android: 'ca-app-pub-5101905792101482/2410178827',
      ios: 'ca-app-pub-5101905792101482/6344225418',
    },
  },

  premium: {
    productId: {
      android: 'full_access',
      ios: 'full_access_dele_spanish_b1',
    },
  },

  writingEvaluationFnName: 'evaluateWritingDeleSpanishB1',

  // Exam Structure - DELE Spanish B1 has unique structure
  examStructure: {
    'grammar': [1, 2],
    'reading': [1, 2, 3],
    'writing': [1, 2],
    'speaking': [1, 2, 3, 4],
    'listening': [1, 2, 3, 4, 5],
  },

  // Declarative Exam Sections Configuration
  sections: [
    {
      id: 'reading',
      order: 1,
      enabled: true,
      menuTitleKey: 'practice.reading.title',
      menuDescriptionKey: 'practice.reading.descriptions.main',
      menuBehavior: 'submenu',
      parts: [
        {
          id: 'reading-1',
          partNumber: 1,
          screenKey: 'ReadingPart1',
          uiComponentKey: 'ReadingPart1UI',
          wrapperKey: 'DeleReadingPart1Wrapper',
          titleKey: 'practice.reading.part1',
          descriptionKey: 'practice.reading.descriptions.part1',
          navTitleKey: 'nav.practice.reading.part1',
          dataLoader: { listMethod: 'getDeleReadingPart1Exams', fetchMethod: 'getDeleReadingPart1ExamById' },
          maxPoints: 5,
          timeMinutes: 14,
          scoringGroup: 'readingWriting',
          mockExamSectionName: 'Comprensión de Lectura',
          mockExamPartName: 'Tarea 1',
          mockExamSectionNumber: 1,
          hasExamSelection: true,
        },
        {
          id: 'reading-2',
          partNumber: 2,
          screenKey: 'ReadingPart2',
          uiComponentKey: 'ReadingPart2UI',
          wrapperKey: 'DeleReadingPart2Wrapper',
          titleKey: 'practice.reading.part2',
          descriptionKey: 'practice.reading.descriptions.part2',
          navTitleKey: 'nav.practice.reading.part2',
          dataLoader: { listMethod: 'getDeleReadingPart2Exams', fetchMethod: 'getDeleReadingPart2ExamById' },
          maxPoints: 5,
          timeMinutes: 14,
          scoringGroup: 'readingWriting',
          mockExamSectionName: 'Comprensión de Lectura',
          mockExamPartName: 'Tarea 2',
          mockExamSectionNumber: 1,
          hasExamSelection: true,
        },
        {
          id: 'reading-3',
          partNumber: 3,
          screenKey: 'ReadingPart3',
          uiComponentKey: 'ReadingPart3UI',
          wrapperKey: 'DeleReadingPart3Wrapper',
          titleKey: 'practice.reading.part3',
          descriptionKey: 'practice.reading.descriptions.part3',
          navTitleKey: 'nav.practice.reading.part3',
          dataLoader: { listMethod: 'getDeleReadingPart3Exams', fetchMethod: 'getDeleReadingPart3ExamById' },
          maxPoints: 5,
          timeMinutes: 14,
          scoringGroup: 'readingWriting',
          mockExamSectionName: 'Comprensión de Lectura',
          mockExamPartName: 'Tarea 3',
          mockExamSectionNumber: 1,
          hasExamSelection: true,
        },
      ],
    },
    {
      id: 'grammar',
      order: 2,
      enabled: true,
      menuTitleKey: 'practice.grammar.title',
      menuDescriptionKey: 'practice.grammar.descriptions.main',
      menuBehavior: 'submenu',
      parts: [
        {
          id: 'grammar-1',
          partNumber: 1,
          screenKey: 'GrammarPart1',
          uiComponentKey: 'GrammarPart1UI',
          wrapperKey: 'DeleGrammarPart1Wrapper',
          titleKey: 'practice.grammar.part1',
          descriptionKey: 'practice.grammar.descriptions.main',
          navTitleKey: 'nav.practice.grammar.part1',
          dataLoader: { listMethod: 'getDeleGrammarPart1Exams', fetchMethod: 'getDeleGrammarPart1ExamById' },
          maxPoints: 5,
          timeMinutes: 14,
          scoringGroup: 'readingWriting',
          mockExamSectionName: 'Bloques de construcción del idioma',
          mockExamPartName: 'Tarea 2',
          mockExamSectionNumber: 2,
          hasExamSelection: true,
        },
        {
          id: 'grammar-2',
          partNumber: 2,
          screenKey: 'GrammarPart2',
          uiComponentKey: 'GrammarPart2UI',
          wrapperKey: 'DeleGrammarPart2Wrapper',
          titleKey: 'practice.grammar.part2',
          descriptionKey: 'practice.grammar.descriptions.main',
          navTitleKey: 'nav.practice.grammar.part2',
          dataLoader: { listMethod: 'getDeleGrammarPart2Exams', fetchMethod: 'getDeleGrammarPart2ExamById' },
          maxPoints: 5,
          timeMinutes: 14,
          scoringGroup: 'readingWriting',
          mockExamSectionName: 'Bloques de construcción del idioma',
          mockExamPartName: 'Tarea 3',
          mockExamSectionNumber: 2,
          hasExamSelection: true,
        },
      ],
    },
    {
      id: 'listening',
      order: 3,
      enabled: true,
      menuTitleKey: 'practice.listening.title',
      menuDescriptionKey: 'practice.listening.comingSoon',
      menuBehavior: 'submenu',
      parts: [
        {
          id: 'listening-1',
          partNumber: 1,
          screenKey: 'ListeningPart1',
          uiComponentKey: 'ListeningPart1UI',
          wrapperKey: 'DeleListeningPart1Wrapper',
          titleKey: 'practice.listening.part1',
          descriptionKey: 'practice.listening.part1Description',
          navTitleKey: 'nav.practice.listening.part1',
          dataLoader: { listMethod: 'getDeleListeningPart1Exams', fetchMethod: 'getDeleListeningPart1ExamById' },
          maxPoints: 5,
          timeMinutes: 8,
          scoringGroup: 'listeningSpeaking',
          mockExamSectionName: 'Comprensión Auditiva',
          mockExamPartName: 'Tarea 1',
          mockExamSectionNumber: 3,
          hasExamSelection: true,
        },
        {
          id: 'listening-2',
          partNumber: 2,
          screenKey: 'ListeningPart2',
          uiComponentKey: 'ListeningPart2UI',
          wrapperKey: 'DeleListeningPart2Wrapper',
          titleKey: 'practice.listening.part2',
          descriptionKey: 'practice.listening.part2Description',
          navTitleKey: 'nav.practice.listening.part2',
          dataLoader: { listMethod: 'getDeleListeningPart2Exams', fetchMethod: 'getDeleListeningPart2ExamById' },
          maxPoints: 5,
          timeMinutes: 8,
          scoringGroup: 'listeningSpeaking',
          mockExamSectionName: 'Comprensión Auditiva',
          mockExamPartName: 'Tarea 2',
          mockExamSectionNumber: 3,
          hasExamSelection: true,
        },
        {
          id: 'listening-3',
          partNumber: 3,
          screenKey: 'ListeningPart3',
          uiComponentKey: 'ListeningPart3UI',
          wrapperKey: 'DeleListeningPart3Wrapper',
          titleKey: 'practice.listening.part3',
          descriptionKey: 'practice.listening.part3Description',
          navTitleKey: 'nav.practice.listening.part3',
          dataLoader: { listMethod: 'getDeleListeningPart3Exams', fetchMethod: 'getDeleListeningPart3ExamById' },
          maxPoints: 5,
          timeMinutes: 8,
          scoringGroup: 'listeningSpeaking',
          mockExamSectionName: 'Comprensión Auditiva',
          mockExamPartName: 'Tarea 3',
          mockExamSectionNumber: 3,
          hasExamSelection: true,
        },
        {
          id: 'listening-4',
          partNumber: 4,
          screenKey: 'ListeningPart4',
          uiComponentKey: 'ListeningPart4UI',
          wrapperKey: 'DeleListeningPart4Wrapper',
          titleKey: 'practice.listening.part4',
          descriptionKey: 'practice.listening.part4Description',
          navTitleKey: 'nav.practice.listening.part4',
          dataLoader: { listMethod: 'getDeleListeningPart4Exams', fetchMethod: 'getDeleListeningPart4ExamById' },
          maxPoints: 5,
          timeMinutes: 8,
          scoringGroup: 'listeningSpeaking',
          mockExamSectionName: 'Comprensión Auditiva',
          mockExamPartName: 'Tarea 4',
          mockExamSectionNumber: 3,
          hasExamSelection: true,
        },
        {
          id: 'listening-5',
          partNumber: 5,
          screenKey: 'ListeningPart5',
          uiComponentKey: 'ListeningPart5UI',
          wrapperKey: 'DeleListeningPart5Wrapper',
          titleKey: 'practice.listening.part5',
          descriptionKey: 'practice.listening.part5Description',
          navTitleKey: 'nav.practice.listening.part5',
          dataLoader: { listMethod: 'getDeleListeningPart5Exams', fetchMethod: 'getDeleListeningPart5ExamById' },
          maxPoints: 5,
          timeMinutes: 8,
          scoringGroup: 'listeningSpeaking',
          mockExamSectionName: 'Comprensión Auditiva',
          mockExamPartName: 'Tarea 5',
          mockExamSectionNumber: 3,
          hasExamSelection: true,
        },
      ],
    },
    {
      id: 'writing',
      order: 4,
      enabled: true,
      menuTitleKey: 'practice.writing.title',
      menuDescriptionKey: 'practice.writing.description',
      menuBehavior: 'submenu',
      parts: [
        {
          id: 'writing-1',
          partNumber: 1,
          screenKey: 'WritingPart1',
          uiComponentKey: 'WritingPart1UI',
          wrapperKey: 'WritingWrapper',
          titleKey: 'practice.writing.part1',
          descriptionKey: 'practice.writing.descriptions.part1',
          navTitleKey: 'nav.practice.writing.part1',
          dataLoader: { listMethod: 'getDeleWritingPart1Exams', fetchMethod: 'getDeleWritingPart1ExamById' },
          maxPoints: 12.5,
          timeMinutes: 30,
          scoringGroup: 'readingWriting',
          scoreScaling: 0.5,
          mockExamSectionName: 'Expresión e Interacción Escritas',
          mockExamPartName: 'Tarea 1',
          mockExamSectionNumber: 4,
          hasExamSelection: true,
        },
        {
          id: 'writing-2',
          partNumber: 2,
          screenKey: 'WritingPart2',
          uiComponentKey: 'WritingPart2UI',
          wrapperKey: 'WritingWrapper',
          titleKey: 'practice.writing.part2',
          descriptionKey: 'practice.writing.descriptions.part2',
          navTitleKey: 'nav.practice.writing.part2',
          dataLoader: { listMethod: 'getDeleWritingPart2Exams', fetchMethod: 'getDeleWritingPart2ExamById' },
          maxPoints: 12.5,
          timeMinutes: 30,
          scoringGroup: 'readingWriting',
          scoreScaling: 0.5,
          mockExamSectionName: 'Expresión e Interacción Escritas',
          mockExamPartName: 'Tarea 2',
          mockExamSectionNumber: 4,
          hasExamSelection: true,
        },
      ],
    },
    {
      id: 'speaking',
      order: 5,
      enabled: true,
      menuTitleKey: 'practice.speaking.title',
      menuDescriptionKey: 'practice.speaking.descriptions.main',
      menuBehavior: 'submenu',
      parts: [
        {
          id: 'speaking-1',
          partNumber: 1,
          screenKey: 'DeleSpeakingAllParts',
          uiComponentKey: 'DeleSpeakingAllPartsUI',
          wrapperKey: 'DeleSpeakingAllPartsWrapper',
          titleKey: 'practice.speaking.part1',
          descriptionKey: 'practice.speaking.descriptions.part1',
          navTitleKey: 'nav.practice.speaking.part1',
          dataLoader: { listMethod: 'getDeleSpeakingPart1Content', fetchMethod: 'getDeleSpeakingPart1Content' },
          maxPoints: 6.25,
          timeMinutes: 3,
          scoringGroup: 'listeningSpeaking',
          mockExamSectionName: 'Expresión e Interacción Orales',
          mockExamPartName: 'Tarea 1: Monólogo',
          mockExamSectionNumber: 5,
          hasExamSelection: false,
          skipInMockExam: true,
        },
        {
          id: 'speaking-2',
          partNumber: 2,
          screenKey: 'DeleSpeakingAllParts',
          uiComponentKey: 'DeleSpeakingAllPartsUI',
          wrapperKey: 'DeleSpeakingAllPartsWrapper',
          titleKey: 'practice.speaking.part2',
          descriptionKey: 'practice.speaking.descriptions.part2',
          navTitleKey: 'nav.practice.speaking.part2',
          dataLoader: { listMethod: 'getDeleSpeakingPart2Content', fetchMethod: 'getDeleSpeakingPart2Content' },
          maxPoints: 6.25,
          timeMinutes: 4,
          scoringGroup: 'listeningSpeaking',
          mockExamSectionName: 'Expresión e Interacción Orales',
          mockExamPartName: 'Tarea 2: Diálogo',
          mockExamSectionNumber: 5,
          hasExamSelection: false,
          skipInMockExam: true,
        },
        {
          id: 'speaking-3',
          partNumber: 3,
          screenKey: 'DeleSpeakingAllParts',
          uiComponentKey: 'DeleSpeakingAllPartsUI',
          wrapperKey: 'DeleSpeakingAllPartsWrapper',
          titleKey: 'practice.speaking.part3',
          descriptionKey: 'practice.speaking.descriptions.part3',
          navTitleKey: 'nav.practice.speaking.part3',
          dataLoader: { listMethod: 'getDeleSpeakingPart3Content', fetchMethod: 'getDeleSpeakingPart3Content' },
          maxPoints: 6.25,
          timeMinutes: 3,
          scoringGroup: 'listeningSpeaking',
          mockExamSectionName: 'Expresión e Interacción Orales',
          mockExamPartName: 'Tarea 3: Conversación',
          mockExamSectionNumber: 5,
          hasExamSelection: false,
          skipInMockExam: true,
        },
        {
          id: 'speaking-4',
          partNumber: 4,
          screenKey: 'DeleSpeakingAllParts',
          uiComponentKey: 'DeleSpeakingAllPartsUI',
          wrapperKey: 'DeleSpeakingAllPartsWrapper',
          titleKey: 'practice.speaking.part4',
          descriptionKey: 'practice.speaking.descriptions.part4',
          navTitleKey: 'nav.practice.speaking.part4',
          dataLoader: { listMethod: 'getDeleSpeakingPart4Content', fetchMethod: 'getDeleSpeakingPart4Content' },
          maxPoints: 6.25,
          timeMinutes: 4,
          scoringGroup: 'listeningSpeaking',
          mockExamSectionName: 'Expresión e Interacción Orales',
          mockExamPartName: 'Tarea 4: Conversación',
          mockExamSectionNumber: 5,
          hasExamSelection: false,
          skipInMockExam: true,
        },
      ],
    },
  ] as ExamSectionConfig[],

  // Mock Exam Configuration
  mockExam: {
    stepOrder: [
      'reading-1', 'reading-2', 'reading-3',
      'grammar-1', 'grammar-2',
      'listening-1', 'listening-2', 'listening-3', 'listening-4', 'listening-5',
      'writing-1', 'writing-2',
      'speaking-1', 'speaking-2', 'speaking-3', 'speaking-4',
    ],
    scoringGroups: [
      {
        id: 'readingWriting',
        labelKey: 'results.deleReadingWriting',
        maxPoints: 50,
        passingPoints: 30,
        sectionNumbers: [1, 2, 4],
      },
      {
        id: 'listeningSpeaking',
        labelKey: 'results.deleListeningSpeaking',
        maxPoints: 50,
        passingPoints: 30,
        sectionNumbers: [3, 5],
      },
    ],
    totalMaxPoints: 100,
    passingTotalPoints: 60,
    skipSectionNumbers: [5],
    scoreMultiplier: 1,
  } as MockExamConfig,
};

